export const bebidas = [
  { nombre: "Té Roost Chicken", check: [], href: "#" },
  { nombre: "Limonada Rosa ", check: [], href: "#" },
  { nombre: "Mojito atrevido ", check: [], href: "#" },
  { nombre: "Botellín Mahou 5 estrellas", check: ["gluten"], href: "#" },
  { nombre: "Cerveza de grifo", check: ["gluten"], href: "#" },
  { nombre: "Vino", check: ["gluten"], href: "#" },
  { nombre: "Tinto de verano", check: ["dioxido"], href: "#" },
  { nombre: "Botellín Mahou IPA", check: ["gluten"], href: "#" },
  { nombre: "Botellín Mahiu Maestra", check: ["gluten"], href: "#" },
  { nombre: "Botellín 0,0% Tostada Mahou", check: ["gluten"], href: "#" },
  { nombre: "Cerveza Corona", check: ["gluten"], href: "#" },
  { nombre: "Cerveza Alhambra 1925", check: ["gluten"], href: "#" },
  { nombre: "Cerveza Polar", check: ["gluten"], href: "#" },
  { nombre: "Botellín Sin gluten mahou 5 estrellas", check: [], href: "#" },
];
