export const burgers = [
  {
    nombre: "Smash Chicken",
    check: [
      "gluten",
      "huevo",
      "soja",
      "lacteos",
      "frutos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
  {
    nombre: "Buucheese",
    check: [
      "gluten",
      "huevo",
      "soja",
      "lacteos",
      "frutos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
  {
    nombre: "The Queen ",
    check: [
      "gluten",
      "huevo",
      "soja",
      "lacteos",
      "frutos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
  {
    nombre: "La Slaw ",
    check: [
      "gluten",
      "huevo",
      "soja",
      "lacteos",
      "frutos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
      "altramuces",
    ],
    href: "#",
  },
  {
    nombre: "Parmayo",
    check: [
      "gluten",
      "huevo",
      "pescado",
      "soja",
      "lacteos",
      "frutos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
      "altramuces",
    ],
    href: "#",
  },
  {
    nombre: "The Original",
    check: [
      "gluten",
      "huevo",
      "soja",
      "lacteos",
      "frutos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
  {
    nombre: "Holly Roost",
    check: [
      "gluten",
      "huevo",
      "soja",
      "lacteos",
      "frutos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
  {
    nombre: "Chicken Gofres",
    check: [
      "gluten",
      "huevo",
      "lacteos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
  {
    nombre: "Chicken pack mix",
    check: [
      "gluten",
      "huevo",
      "soja",
      "lacteos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
];
