const entrantes = [
  {
    nombre: "Macaroni",
    check: [
      "gluten",
      "huevo",
      "soja",
      "lacteos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
  { nombre: "Tequeños", check: ["gluten", "lacteos"], href: "#" },
  {
    nombre: "Nachos Roost chicken",
    check: ["gluten", "lacteos", "apio", "mostaza", "granos"],
    href: "#",
  },
  {
    nombre: "Crispy Wings",
    check: [
      "gluten",
      "huevo",
      "pescado",
      "lacteos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
  {
    nombre: "Crazy Cheese Fries",
    check: [
      "gluten",
      "pescado",
      "lacteos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
  {
    nombre: "Super Roost Chicken",
    check: [
      "gluten",
      "huevo",
      "soja",
      "lacteos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
      "altramuces",
    ],
    href: "#",
  },
  {
    nombre: "Fingers & Fries",
    check: [
      "gluten",
      "huevo",
      "pescado",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
  {
    nombre: "Las fajitas de María",
    check: [
      "gluten",
      "huevo",
      "pescado",
      "soja",
      "lacteos",
      "apio",
      "mostaza",
      "granos",
      "dioxido",
    ],
    href: "#",
  },
  {
    nombre: "Patatas finas con especias",
    check: ["gluten", "apio", "mostaza", "granos", "dioxido"],
    href: "#",
  },
  {
    nombre: "Patatas gajos con especias",
    check: ["gluten", "apio", "mostaza", "granos", "dioxido"],
    href: "#",
  },
  {
    nombre: "Boniato con especias",
    check: ["gluten", "apio", "mostaza", "granos", "dioxido"],
    href: "#",
  },
];

export default entrantes;
